import { WINGET_PACKAGE_IDS } from './wingetExeBuilder.mjs'

const MAX_SCRIPT_FILENAME_LENGTH = 80

const sanitizeBaseName = (value) =>
  String(value || '')
    .trim()
    .replace(/[^A-Za-z0-9]+/g, '_')
    .replace(/^_+|_+$/g, '')
    .slice(0, MAX_SCRIPT_FILENAME_LENGTH)

const escapeSingleQuotes = (value) => String(value).replace(/'/g, "''")

const normalizeSelectedApps = (apps) =>
  apps.map((appId) => {
    const packageId = WINGET_PACKAGE_IDS[appId]
    if (!packageId) {
      throw new Error(`No package mapping configured for app: ${appId}`)
    }

    return {
      id: appId,
      packageId,
    }
  })

export const createScriptFilename = (name) => {
  const baseName = sanitizeBaseName(name) || 'CorgiNite_Bundle'
  return `${baseName}.ps1`
}

export const buildInstallerScript = ({ payload }) => {
  const selectedApps = normalizeSelectedApps(payload.apps)
  const selectedAppsJson = JSON.stringify(selectedApps, null, 2)
  const scriptName = escapeSingleQuotes(payload.name)
  const shouldSilentInstall = payload.options.silentInstall ? '$true' : '$false'
  const shouldCreateRestorePoint = payload.options.restorePoint ? '$true' : '$false'

  return `# CorgiNite installer bootstrap
# Generated by CorgiNite
# Run this script from an elevated PowerShell window.

param()

$ErrorActionPreference = 'Stop'
Set-StrictMode -Version Latest

$InstallerName = '${scriptName}'
$SilentInstall = ${shouldSilentInstall}
$CreateRestorePoint = ${shouldCreateRestorePoint}
$SelectedApps = @'
${selectedAppsJson}
'@ | ConvertFrom-Json

function Test-Administrator {
  $currentIdentity = [System.Security.Principal.WindowsIdentity]::GetCurrent()
  $principal = [System.Security.Principal.WindowsPrincipal]::new($currentIdentity)
  return $principal.IsInRole([System.Security.Principal.WindowsBuiltInRole]::Administrator)
}

function Restart-WithElevation {
  if (Test-Administrator) {
    return
  }

  Write-Host 'Requesting administrator privileges...'
  $arguments = @(
    '-NoProfile',
    '-ExecutionPolicy', 'Bypass',
    '-File', $PSCommandPath
  )
  Start-Process -FilePath 'powershell.exe' -Verb RunAs -ArgumentList $arguments | Out-Null
  exit 0
}

function Test-Command {
  param([Parameter(Mandatory = $true)][string]$Name)
  return [bool](Get-Command $Name -ErrorAction SilentlyContinue)
}

function Ensure-Chocolatey {
  if (Test-Command 'choco') {
    return
  }

  Write-Host 'Chocolatey is missing. Bootstrapping it as a fallback dependency manager...'
  [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor [System.Net.SecurityProtocolType]::Tls12
  Set-ExecutionPolicy Bypass -Scope Process -Force
  Invoke-Expression ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))

  if (-not (Test-Command 'choco')) {
    throw 'Chocolatey bootstrap failed.'
  }
}

function Start-RestorePoint {
  if (-not $CreateRestorePoint) {
    return
  }

  try {
    Checkpoint-Computer -Description $InstallerName -RestorePointType 'MODIFY_SETTINGS' | Out-Null
    Write-Host 'Restore point created.'
  } catch {
    Write-Warning "Restore point skipped: $($_.Exception.Message)"
  }
}

function Install-WithWinget {
  param([Parameter(Mandatory = $true)]$App)

  $arguments = @(
    'install',
    '--id', $App.packageId,
    '--exact',
    '--source', 'winget',
    '--accept-package-agreements',
    '--accept-source-agreements',
    '--disable-interactivity'
  )

  if ($SilentInstall) {
    $arguments += '--silent'
  }

  Write-Host "Installing $($App.id)..."
  & winget @arguments

  if ($LASTEXITCODE -ne 0) {
    throw "winget failed while installing $($App.id)."
  }
}

Restart-WithElevation

if (-not (Test-Command 'winget')) {
  Ensure-Chocolatey
  throw 'winget is required to install the selected apps. Chocolatey was installed as a fallback dependency manager, but App Installer is still needed for the exact package IDs.'
}

Start-RestorePoint

foreach ($app in $SelectedApps) {
  Install-WithWinget -App $app
}

Write-Host ''
Write-Host "Finished installing $InstallerName."
Write-Host 'If the selected apps were already installed, winget may have skipped or repaired them.'
`
}